SELECT DATE_FORMAT(a.DATETIME, '%H') AS "HOUR", count("HOUR") AS "COUNT"
  FROM ANIMAL_OUTS a
 WHERE DATE_FORMAT(a.DATETIME, '%H') between 9 and 19
 GROUP BY DATE_FORMAT(a.DATETIME, '%H')
 ORDER BY HOUR;